### ISSUE TITLE
relay server reports empty list of networks when starting

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/relay#189]
when starting the relay server, it reports an empty list of networks. It looks like it needs to initialize first.

```
~/trustlines/relay (git)-[develop] % http https://staging.testnet.trustlines.network/api/v1/networks
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 3
Content-Type: application/json
Date: Thu, 23 Aug 2018 06:39:20 GMT

[]

~/trustlines/relay (git)-[develop] % http https://staging.testnet.trustlines.network/api/v1/networks
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 3
Content-Type: application/json
Date: Thu, 23 Aug 2018 06:39:25 GMT

[]

~/trustlines/relay (git)-[develop] % http https://staging.testnet.trustlines.network/api/v1/networks
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 3
Content-Type: application/json
Date: Thu, 23 Aug 2018 06:39:27 GMT

[]

~/trustlines/relay (git)-[develop] % http https://staging.testnet.trustlines.network/api/v1/networks
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 3
Content-Type: application/json
Date: Thu, 23 Aug 2018 06:39:28 GMT

[]

~/trustlines/relay (git)-[develop] % http https://staging.testnet.trustlines.network/api/v1/networks
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 3
Content-Type: application/json
Date: Thu, 23 Aug 2018 06:39:30 GMT

[]

~/trustlines/relay (git)-[develop] % http https://staging.testnet.trustlines.network/api/v1/networks
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 305
Content-Type: application/json
Date: Thu, 23 Aug 2018 06:39:49 GMT

[
    {
        "abbreviation": "CASH",
        "address": "0xc5F45B680e81759E3FBc4b4a5A94FBd40BAB3fAd",
        "name": "Cash"
    },
    {
        "abbreviation": "BEER",
        "address": "0x4ddD82891D9c6E46Ec9A6713d032f923919A8349",
        "name": "Beers"
    },
    {
        "abbreviation": "WORK",
        "address": "0x643Ab3543BdF755EbC28A8228098Dd9569c4F4dc",
        "name": "Work Hours"
    }
]

```

**Comment by berndbohmeier** [comment]
What is the bug there? It needs some time to start up, dont know how we can fix that, we could only change the order.

**Comment by schmir** [comment]
> What is the bug there?

Do I really have to explain?

**Comment by schmir** [comment]
The documentation states for the /network endpoint "Returns all registered currency networks with high-level information."

There were three networks configured in the server via the addresses.json file.

The client asks for this information, and get's an empty list as a result. This is the bug. The server should have returned high-level information about those currency networks. It didn't do this. The last few lines above contain the right response, which the server should have given back:
```
[
    {
        "abbreviation": "CASH",
        "address": "0xc5F45B680e81759E3FBc4b4a5A94FBd40BAB3fAd",
        "name": "Cash"
    },
    {
        "abbreviation": "BEER",
        "address": "0x4ddD82891D9c6E46Ec9A6713d032f923919A8349",
        "name": "Beers"
    },
    {
        "abbreviation": "WORK",
        "address": "0x643Ab3543BdF755EbC28A8228098Dd9569c4F4dc",
        "name": "Work Hours"
    }
]
``` 

Is this now clear enough?

**Comment by berndbohmeier** [comment]
No, for me what was not clear is what should it respond instead? Should it not answer until it is ready?

**Comment by schmir** [comment]
IMO it should not respond with a wrong answer. 

My assumption at the moment is, that this endpoint is only  one of the endpoints that gives back wrong result until the server has finished initializing it's data structures. This may take longer than a client might be willing to wait for a response.

We might return HTTP Status Code 503 with a RETRY-AFTER header, when the server isn't fully initialized yet:
```
10.5.4 503 Service Unavailable

The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay MAY be indicated in a Retry-After header. If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response.

      Note: The existence of the 503 status code does not imply that a
      server must use it when becoming overloaded. Some servers may wish
      to simply refuse the connection.
```

or we might just not listen for new requests until the server is initialized. I would do the latter if we see a need to fix this issue.

**Comment by schmir** [comment]
I've been looking into this a bit more. I can't reproduce this issue when starting commands in the terminal - unless I stop parity.
In that case, tl-relay shows an error and apparently it will only answer correctly after `_start_listen_on_new_addresses` was able to call `_load_addresses` successfully.

**Comment by andfletcher** [comment]
Closing this since its not a serious issue and can be reopened once its more pressing.
