### ISSUE TITLE
Use low gas price option

### ISSUE THREAD

**Issue by heikoheiko** [trustlines-protocol/relay#2]
Transfer cost is a major issue. Therefore we could use a low gas price and still get the transactions mined. We are building the system to initially confirm transactions to a user based on their acceptance on a pending block and giving finality probability info. 

So relays would need to keep a pool of pending trustlines transactions and replay them to the new block candidate, whenever a new block is received, to stay in sync. 

To easily filter for trustlines txs it would make sense to have a single contract managing all user accounts. Otherwise we'd need maintain and check a list of all trustlines related user proxy contracts (also doable).

http://ethgasstation.info/

**Comment by andfletcher** [comment]
Outdated with current architecture. Reopen and explain if not.
