### ISSUE TITLE
Describe development setup

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#207]
The README is outdated and does not describe how to get a test version of the relay server running.
Update that with an explanation of how to set it up with docker-compose, and optional how to set it up manually. 
Also document how to run tests so that you can contribute code.

**Comment by andfletcher** [comment]
@schmir-at-bb please check if this still has any value or if this is done with the current changes that have been done in the documentation

**Comment by schmir-at-bb** [comment]
I would say it's done.
