### ISSUE TITLE
Enhance AnyEventSchema

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/relay#209]
`AnyEvenySchema` dispatches based on an object being an instance of a class. The object itself will actually be an instance of said subclass, but `get_obj_type` will return the same value for all subclasses.

This makes it impossible to load that result via marshmallow and get the same objects back (i.e. their class will differ).

Maybe we should dispatch based on the type field, or use `OneOfSchema`'s default implementation and register all subclasses in `type_schemas`

**Comment by andfletcher** [comment]
Closing this since not relevant anymore.
