### ISSUE TITLE
Max capacity REST endpoint for receiver pays

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#272]
Endpoint to ask for maximum capacity for a transfer where the receive pays.
So far it is not clear what exactly max capacity means in this context.

**Comment by berndbohmeier** [comment]
This is deferred for now, as we have no clear vision of how this will be used.

**Comment by andfletcher** [comment]
Related to https://github.com/trustlines-protocol/relay/issues/273, therefore closing.
