### ISSUE TITLE
Balance endpoint returns balance in ether

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#274]
The balance endpoint returns the balance in ether and not in wei. To be more inline with that every other endpoint returns the smallest unit, this should also return wei.

**Comment by berndbohmeier** [comment]
Also this endpoint seems not to be documented.

**Comment by andfletcher** [comment]
@schmir-at-bb could you check if this has been documented by now since you went through the relay documentation just recently.

**Comment by schmir-at-bb** [comment]
It's documented: https://github.com/trustlines-protocol/relay/blob/master/docs/RelayAPI.md#balance-of-user

I would just close this issue (in order to not break stuff).

**Comment by schmir-at-bb** [comment]
Please also fix the documentation and add an entry to to the change log, because this is a breaking change.

**Comment by cducrest** [comment]
done
