### ISSUE TITLE
Upgrade marshmallow

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#305]
We should upgrade the marshmallow lib. Lot of the documentation is wrong, because there is a new version out that did a lot of breaking changes. The breaking changes make sense, so we should upgrade sooner than later. 
This probably caused the bug that we just had with the missing field.

**Comment by cducrest** [comment]
See: https://github.com/trustlines-protocol/relay/pull/306
for anyone that wants to pick this up

**Comment by schmir-at-bb** [comment]
#306 has been merged
