### ISSUE TITLE
Make logging setting changeable similar to the bridge

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#332]
In the bridge we have found a good way to be easy able to config the logging settings. 
We should do the same for the relay server. 
We should use this also to change the config file format to toml like in the bridge.

**Comment by cducrest** [comment]
first draft: https://github.com/trustlines-protocol/relay/compare/feature/config-logging?expand=1

**Comment by schmir-at-bb** [comment]
This is implemented in https://github.com/trustlines-protocol/relay/pull/339
