### ISSUE TITLE
Change config of delegate fees

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#357]
Currently the config takes two values, `value` and `currencyNetwork`. Both are written as single noun, but apparently take a list. This is not intuitive and I dont know how it should work. 
Probably the proper solution is to take a list of pairs of (currencyNetwork, value)

**Comment by schmir-at-bb** [comment]
The way to do this is to specify multiple sections:
```
[[relay.delegationFees]]
value = 2
currencyNetwork = "0x002..."

[[relay.delegationFees]]
value = 1
currencyNetwork = "0x0001...."
```
This gives the following data structure:
```
In [9]: d["relay"]["delegationFees"]                                            
Out[9]: 
[{'value': 2, 'currencyNetwork': '0x002...'},
 {'value': 1, 'currencyNetwork': '0x0001....'}]
```
(This is what I meant with https://github.com/trustlines-protocol/relay/pull/353#pullrequestreview-322141476)
