### ISSUE TITLE
Replace use of erc20 methods

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/relay#362]
We removed erc20 related methods from CN and need to see if they were used in the relay server to remove / replace them.  (balanceOf, totalSupply, spendable, ..)

**Comment by weilbith** [comment]
- `balanceOf` only used in context of the UnwETH, Token and Exchange contract, which have been not affected by the [related PR](https://github.com/trustlines-protocol/contracts/pull/275)
- `totalSupply`isn't used at all
- `spendable`/`spendableTo` is defined for the currency network proxy <-- needs action
