### ISSUE TITLE
Add script to fetch currency network contracts from registry

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/relay#404]
should support filter for registering address

**Comment by weilbith** [comment]
Postponed for maybe later. A prototype exists and could be used. But there are too many open design questions for such an debatable feature. Therefore we will simply add some `addresses.json` files for the both chains. Maybe I will provide a major version over weekend or so.

**Comment by weilbith** [comment]
I additionally want to dump the feedback of Ralf, which he gave me in a call for the prototype I have written voluntary:
  - move tool as sub-package of relay, but preserve the additional entry point
  - have defaults per chain, ask the RPC endpoint for the chain ID and mix them
  - get rid of `AddressFile` class in favor of a single function
  - maybe do not split CLI options into separated file (was meant to increase readability)

**Comment by cducrest** [comment]
No
