### ISSUE TITLE
Allow to enable different types of the api

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#413]
As a fast approach to be able to run the relay server for different use cases and thus needing different functionalities, we will allow to only enable certain api functionalities. The long goal would be most likely to separate those functionality completly into different programs. 

The different apis are:
- Delegate (disabled per default) 
- Pathfinding (enabled per default)
- Events (enabled per default)
- Exchange (disabled per default)
- Transaction relaying (disabled per default)
- messaging (disabled per default)
- push-notification (disabled per default)

This is my suggestions, and can be changed if needed.

**Comment by schmir-at-bb** [comment]
> The long goal would be most likely to separate those functionality completly into different programs.

This doesn't make any sense to me. If you can turn different APIs on or off at will, why should different programs be necessary. Can you explain the reasoning behind that?

**Comment by berndbohmeier** [comment]
I would assume that smaller application are easier to maintain and give more flexibility in the long run. For example we could even use different languages. 
But this I not a decision, we might never do that.

**Comment by berndbohmeier** [comment]
Done
