### ISSUE TITLE
Account summary address

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/relay#460]
When working on the endpoint for list of trustlines for a CN, I encountered this: 
https://github.com/trustlines-protocol/relay/blob/master/src/relay/api/resources.py#L198

We return a field `address` which is undocumented for example when asking for the TL of a user in a CN: https://github.com/trustlines-protocol/relay/blob/master/docs/RelayAPI.md#trustlines-of-user-in-currency-network

Can it be removed @berndbohmeier ?

**Comment by berndbohmeier** [comment]
I guess this is a leftover and is deprecated, so  yes we should remove it I guess.
