### ISSUE TITLE
Refactor event querying from event index

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#484]
After removing the old code event querying code we can now refactor the index code to better match the needs. 
For that I would like to separate the general database contract querying (ex: get all events with for contract) code from the specific trustline related code (get all trustline updates).
We need to still ensure that one database connection is not used by more than one greenlet (is not shared between greenlets), for us these means to not share them for different REST requests, as we spawn a greenlet for each REST request.

**Comment by cducrest** [comment]
Done
