### ISSUE TITLE
Add tests for event querying from database

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#485]
We want have the same tests that we currently have for example for the transfer information tests run against the event database. For that we need to find out a good way to test postgres queries and how to fill the database with the right events.

**Comment by andfletcher** [comment]
to be reevaluated if we need to do this.

**Comment by cducrest** [comment]
I think a way to achieve this would be to run a database and eth-index, then to make eth-index include events from the tester chain of eth_tester.

That way we could reuse the way we test events locally in unit tests of the relay to populate the database.

**Comment by cducrest** [comment]
Done
