### ISSUE TITLE
Investigate why relay seems to stop processing

### ISSUE THREAD

**Issue by compojoom** [trustlines-protocol/relay#508]
It seems that at one point after running for a lot of time the relay stops processing events. There is nothing sent over websocket and the trustline endpoint reports wrong trustline values. 

To investigate this I'll write a script that creates a trustline between 2 users and constantly updates it. After each update the script will check the trustline endpoint and check that it reports the expected values.

**Comment by berndbohmeier** [comment]
So far we could not identify the cause of completely stopping of event processing, as we were not able to reproduce it.

**Comment by compojoom** [comment]
https://sentry.io/organizations/brainbot/issues/1802300732/?project=1214672&query=is%3Aunresolved

This seems to have happened at about the same time when balance updates stopped processing.

**Comment by compojoom** [comment]
I managed to play with that yesterday and sadly couldn't figure out a way to reproduce the original problem. 

I had my private dev. chain running with openethereum, py-eth-index, postgre and obviously the relay. 

I started a script that was creating a trustline and constantly updating it. 
I was stopping the ethereum node and starting it again - the trustline updates afterwards were working fine.

I killed the ethindex script, database etc - trustline updates were fine. 

I was able to reproduce `FATAL: remaining connection slots are reserved for non-replication superuser connections`error that we see on sentry though. I sent 1000 requests in parallel to the /events endpoint for the same user and obviously the database server chocked on it. But it seemed like the db server just closed the extra connections and served data over the connections it could handle. Afterwards everything seemed to further work fine.

**Comment by compojoom** [comment]
Today, the impossible happened! The dev. server stopped processing trustline updates. 
The difference with the relay operated by anyblock and the dev. server is that the dev server is not processing events for a single address:
0xF2e5E2069D4acCa634EFFfA4aeDFC8655750641a

`http://165.227.144.121:5000/api/v1/networks/0x7146025e6B296b7dAcb68C6981C8F2dEDEd24C4D/users/0xF2e5E2069D4acCa634EFFfA4aeDFC8655750641a/trustlines/0x23d53e6F29937b133A40e6407D6dF3e6dBB99191`

The call to the trustlines endpoint returns a 0 trustline.

I can see that there is a trustlineUpdate event for this trustline in the database:
```
transactionhash,blocknumber,address,eventname,args,blockhash,transactionindex,logindex,timestamp
0xfc7de410e53ac5af2a5e9db1280d64d363a4d4790f99f9e6761aadf213d5c441,1858435,0xd671328535E2e522196c526bB77B14A07bac53Ba,Onboard,"{""_onboardee"": ""0x23d53e6F29937b133A40e6407D6dF3e6dBB99191"", ""_onboarder"": ""0xF2e5E2069D4acCa634EFFfA4aeDFC8655750641a""}",0xc04851358958f9e179692062ad0e9b5fa6be73a35ddbd0ac87d280e8702eeecb,0,0,1597049140
0xfc7de410e53ac5af2a5e9db1280d64d363a4d4790f99f9e6761aadf213d5c441,1858435,0xd671328535E2e522196c526bB77B14A07bac53Ba,TrustlineUpdate,"{""_debtor"": ""0x23d53e6F29937b133A40e6407D6dF3e6dBB99191"", ""_creditor"": ""0xF2e5E2069D4acCa634EFFfA4aeDFC8655750641a"", ""_isFrozen"": false, ""_creditlineGiven"": 1000, ""_interestRateGiven"": 0, ""_creditlineReceived"": 1000, ""_interestRateReceived"": 0}",0xc04851358958f9e179692062ad0e9b5fa6be73a35ddbd0ac87d280e8702eeecb,0,1,1597049140

```

The generated in memory graph however doesn't seem to contain the trustline.

I'll wait for @cducrest to debug together. So far it seems that this is consistent - I have restarted the relay like 100 times today and this trustline is missing.

**Comment by cducrest** [comment]
The network in your request is not the correct one. In your http address you have `/networks/0x7146025e6B296b7dAcb68C6981C8F2dEDEd24C4D` but in the database there is address `0xd671328535E2e522196c526bB77B14A07bac53Ba`.

If you correct that and query `http://165.227.144.121:5000/api/v1/networks/0xd671328535E2e522196c526bB77B14A07bac53Ba/users/0xF2e5E2069D4acCa634EFFfA4aeDFC8655750641a/trustlines/0x23d53e6F29937b133A40e6407D6dF3e6dBB99191` you indeed get a TL for 1000/1000 and 0 interests.

**Comment by compojoom** [comment]
I haven't seen this in a while. It's possible that it was a bug within the app that somehow mixes the network addresses.
I'll close this for now.
