### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#514]
We want to update and improve the documentation. 

Todos:
- [ ] Create file `Contributing` and explain what is necessary to contribute
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
- [ ] Decide what should happen to `RelayServer.md`
- [ ] Add explanation on releasing
- [ ] Add gitter badge
- [ ] Add example in beginning
- [ ] Section for Licence

**Comment by cducrest** [comment]
Task list moved to project issue: https://github.com/trustlines-network/project/issues/879
