### ISSUE TITLE
Graph changes are sometimes missing

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#523]
We saw that sometimes graph changes are missing. This seems to be a race condition between the normal event updating and the complete graph resync. The complete graph sync is there to deal with reorgs. The planned way forward is to redo and properly fix the handling of reorgs. 
See https://github.com/trustlines-protocol/relay/issues/522.

**Comment by cducrest** [comment]
Fixed by updating graph sync
