### ISSUE TITLE
Better configuration of the application

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#94]
The relay instance should be easier to configure and with more options. 
We should discuss if .json is the right format, or if there is a more pythonic way. 
Also we should support command line parameters.

**Comment by berndbohmeier** [comment]
I would say json is enough for now and we dont need command line parameter just yet.

**Comment by andfletcher** [comment]
This has been done. Closing. Followup issue: https://github.com/trustlines-network/project/issues/763
